DROP TABLE vendor_questionary_interview;
DROP TABLE vendor_questionary_question;
DROP TABLE vendor_questionary_option;
DROP TABLE vendor_questionary_answer_result;
DROP TABLE vendor_questionary_answer_to_question;
DROP TABLE vendor_questionary_answer_option;
